### ISSUE TITLE
OverflowException for far north/south latitudes especially during polar day/night

### ISSUE THREAD

**Issue by JonMcPherson** [porrey/Solar-Calculator#6]
The calculation overflows for locations that are closer to the poles (~ ±65° latitude) especially for dates during polar day or night.
```
Unhandled Exception: System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Double value)
   at Innovative.SolarCalculator.Universal.Math.Acos(Decimal value)
   at Innovative.SolarCalculator.SolarTimes.get_HourAngleSunrise()
   at Innovative.SolarCalculator.SolarTimes.get_Sunrise()
```

Example:
```csharp
// Tromsø, Norway during polar night (overflows even for less extreme cases)
new SolarTimes(new DateTime(2020, 1, 1), new Angle(69.6529), new Angle(18.9641))
```

**Comment by JonMcPherson** [comment]
I'd like to be able to know exactly when the next sunrise or sunset is even if it is over 24 hours (like this does https://www.timeanddate.com/sun/@69.6529,18.9641)

**Comment by JonMcPherson** [comment]
@porrey any thoughts on this?

**Comment by porrey** [comment]
> I'd like to be able to know exactly when the next sunrise or sunset is even if it is over 24 hours (like this does https://www.timeanddate.com/sun/@69.6529,18.9641)

Pass a future date when creating the instance.

SolarTimes solarTimes = new SolarTimes(DateTime.Now.Date.AddDays(10), 41.9032, -87.6224);

**Comment by porrey** [comment]
> The calculation overflows for locations that are closer to the poles (~ ±66° latitude) especially for dates during polar day or night.
> 
> ```
> Unhandled Exception: System.OverflowException: Value was either too large or too small for a Decimal.
>    at System.Decimal..ctor(Double value)
>    at Innovative.SolarCalculator.Universal.Math.Acos(Decimal value)
>    at Innovative.SolarCalculator.SolarTimes.get_HourAngleSunrise()
>    at Innovative.SolarCalculator.SolarTimes.get_Sunrise()

This has to do with two factors. First, as you get closer to the poles the assumptions used in the model start to break down. This leads to the second issue where the fact that in some cases, the math results in a Double.NaN or Double.NegativeInfinity or even Double.PositiveInfinity, these do not translate to decimal and result in an overflow error. The code uses decimal where possible because with double, the calculations produce enough error to make the resulting times wrong.

I will investigate better ways to handle this.

**Comment by JoeSchulte** [comment]
Any chance of an update for this?

**Comment by Nickztar** [comment]
I've solved this. Not sure what the best way to support it is. There are some options to this, none of which are perfect in anyway.

1. Prevent the overflow and have two new variables that indicate that it is Polar day/Polar night. For day: Sunset will be 24h from sunrise, sunrise is something like a few minutes of the start of the day, which is not really correct.
2. Correct Sunrise and Sunset to be when the sun last rose, Could be weeks ago. Same for sunset. This way the properies actually show the correct thing. 
3. Add a new Sunrise & Sunset which can be corrected for Polar Night/Day. 

Currently I am just recursivly solving for when the sun last rose, might be a smarter way to solve this.

It is still a work in progress but if you have a preference on how this should be handled, please leave a comment.

Here is my currently progress:
https://github.com/Nickztar/Solar-Calculator/commit/e83eb4e76b364c0efa5eea3f2b17fc0223032b22

**Comment by porrey** [comment]
Thank you, I appreciate your help on this.

I would prefer option 2 as it provides backwards compatibility but recursively solving for that could add undue overhead. 

Option 1 might be better, except set Sunrise to Sunset to DateTime.MinValue. This would provide a testable output to know when to check new variables.

The ideal behavoir would be that when it is polar day, the property IsPolarDay = true, IsPolarNight = false, Sunrise = DateTime.MinValue and Sunset would be the next sunset date and time. When it is polar night, IsPolarNight = true, IsPolarDay = false, Sunset = DateTime.MinValue and Sunrise is set to then ext sunrise date and time.

The better to solve for polar data and night is to do the math/geometry which would take more research. Recursively finding it may work as long as the recursion is finite.

**Comment by Nickztar** [comment]
Thanks for the input. I agree with the backwards compatability but not fully happy with having to do it recursivly. Will try and do some more research. Also the current check for polar day is not perfect. 

Option 1 feels very safe (as long as the detection is correct). An another alternative is setting it to null, would be a much bigger breaking change but might be more correct that Max/Min value?

**Comment by porrey** [comment]
Changing the value type to nullable would cause breaking changes. Using MinDate will work for now. I could create a custom return type with implicit operators to and from DateTime that would allow extension of the return type.

**Comment by Nickztar** [comment]
Let's go with option 1 then, with the change for returning Min/Max value.

This will at least prevent the overflow issue and allows people to continue using it and in their own way calculate the next sunrise etc recursively. Might do some more research in the future for solving this correctly.

Will send a PR tomorrow.

**Comment by JoeSchulte** [comment]
I would like to see the addition of Polar Day and Night as bools, that way you know if the other values are not the same day or set to min/max values.

**Comment by porrey** [comment]
the properties are called **IsPolarDay** and **IsPolarNight**.
